import { api } from './api';

export type Environment = 'CLOUD' | 'ONPREM' | 'HYBRID';
export type ModelStatus = 'DRAFT' | 'REVIEW' | 'APPROVED' | 'ARCHIVED';
export type StrideCategory =
  | 'SPOOFING'
  | 'TAMPERING'
  | 'REPUDIATION'
  | 'INFO_DISCLOSURE'
  | 'DENIAL_OF_SERVICE'
  | 'ELEVATION_OF_PRIVILEGE';
export type ThreatStatus = 'OPEN' | 'MITIGATED' | 'ACCEPTED' | 'FALSE_POSITIVE';
export type DataClassification = 'PUBLIC' | 'INTERNAL' | 'CONFIDENTIAL' | 'SECRET';

export interface ThreatModelSummary {
  id: string;
  name: string;
  description: string;
  environment: Environment;
  status: ModelStatus;
  createdByName: string | null;
  createdAt: string;
  updatedAt: string;
  _count: { components: number; dataFlows: number; threats: number };
}

export interface TmComponent {
  id: string;
  modelId: string;
  name: string;
  componentType: string;
  environment: 'CLOUD' | 'ONPREM';
  cloudProvider: string | null;
  serviceName: string | null;
  notes: string | null;
  createdAt: string;
}

export interface TmDataFlow {
  id: string;
  modelId: string;
  name: string;
  protocol: string;
  dataClassification: DataClassification;
  isEncrypted: boolean;
  crossesTrustBoundary: boolean;
  notes: string | null;
  createdAt: string;
  source: { id: string; name: string; componentType: string };
  target: { id: string; name: string; componentType: string };
}

export interface TmThreat {
  id: string;
  modelId: string;
  componentId: string | null;
  flowId: string | null;
  title: string;
  description: string;
  strideCategory: StrideCategory;
  attackTactic: string;
  attackTechnique: string;
  likelihood: number;
  impact: number;
  riskScore: number;
  status: ThreatStatus;
  mitigationNotes: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  component?: { id: string; name: string; componentType: string } | null;
  flow?: { id: string; name: string } | null;
}

export interface ThreatModelDetail extends ThreatModelSummary {
  components: TmComponent[];
  dataFlows: TmDataFlow[];
  threats: TmThreat[];
}

export interface RiskSummary {
  total: number;
  open: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
  byStride: Record<string, number>;
  byStatus: Record<string, number>;
}

// ── API functions ─────────────────────────────────────────────────────────────

export const listModels = () => api.get<ThreatModelSummary[]>('/threat-models');

export const createModel = (data: {
  name: string;
  description?: string;
  environment: Environment;
}) => api.post<ThreatModelSummary>('/threat-models', data);

export const getModel = (id: string) => api.get<ThreatModelDetail>(`/threat-models/${id}`);

export const updateModelStatus = (id: string, status: ModelStatus) =>
  api.patch<{ id: string; status: ModelStatus }>(`/threat-models/${id}/status`, { status });

export const deleteModel = (id: string) => api.delete<{ deleted: boolean }>(`/threat-models/${id}`);

export const addComponent = (
  modelId: string,
  data: {
    name: string;
    componentType: string;
    environment: 'CLOUD' | 'ONPREM';
    cloudProvider?: string;
    serviceName?: string;
    notes?: string;
  },
) => api.post<TmComponent>(`/threat-models/${modelId}/components`, data);

export const deleteComponent = (modelId: string, componentId: string) =>
  api.delete<{ deleted: boolean }>(`/threat-models/${modelId}/components/${componentId}`);

export const addFlow = (
  modelId: string,
  data: {
    name: string;
    sourceId: string;
    targetId: string;
    protocol?: string;
    dataClassification?: DataClassification;
    isEncrypted?: boolean;
    crossesTrustBoundary?: boolean;
    notes?: string;
  },
) => api.post<TmDataFlow>(`/threat-models/${modelId}/flows`, data);

export const deleteFlow = (modelId: string, flowId: string) =>
  api.delete<{ deleted: boolean }>(`/threat-models/${modelId}/flows/${flowId}`);

export const generateThreats = (modelId: string) =>
  api.post<{ generated: number; message?: string }>(
    `/threat-models/${modelId}/generate-threats`,
    {},
  );

export const listThreats = (modelId: string) =>
  api.get<TmThreat[]>(`/threat-models/${modelId}/threats`);

export const updateThreat = (
  modelId: string,
  threatId: string,
  data: { status?: ThreatStatus; likelihood?: number; impact?: number; mitigationNotes?: string },
) => api.patch<TmThreat>(`/threat-models/${modelId}/threats/${threatId}`, data);

export const deleteThreat = (modelId: string, threatId: string) =>
  api.delete<{ deleted: boolean }>(`/threat-models/${modelId}/threats/${threatId}`);

export const getRiskSummary = (modelId: string) =>
  api.get<RiskSummary>(`/threat-models/${modelId}/risk-summary`);
