INSERT INTO detections (
  rule_id, name, description, severity, platform,
  mitre_attack_id, mitre_tactic, mitre_technique,
  nist_controls, data_sources, query, query_language, tags,
  expected_alerts_per_day, expected_fp_rate, expected_mttd_hours,
  is_global, tenant_id, log_sources, device_types
) VALUES
('DET-0176', 'Unrouteable Activity Detected', 'Alerts when activity to or from a host that is unrouteable is detected.', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1046', 'Discovery', 'Network Service Scanning', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Network Communication"}', '{"Firewall","Network Device"}'),
('DET-0177', 'New Application Accessing Salesforce.com API', 'Salesforce.com contains the most critical information for many companies. This search looks for users who connect to SFDC''s reporting API with new clients. Alert Volume: Low', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1213', 'Collection', 'Data from Information Repositories', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Audit Trail"}', '{"Audit System"}'),
('DET-0178', 'Detect Log Clearing With wevtutil', 'This use case looks for the wevutil process clearing the Windows Audit LogsAlert Volume: Low', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1070', 'Defense Evasion', 'Indicator Removal on Host', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Endpoint Detection and Response","Windows Security"}', '{"EDR","Endpoint","Windows AD","Windows Endpoint"}'),
('DET-0179', 'USN Journal Deletion', 'The fsutil.exe application is a legitimate Windows utility used to perform tasks related to the file allocation table (FAT) and NTFS file systems. The update sequence number (USN) change journal provides a log of all changes made to the files on the disk. This search looks for fsutil.exe deleting the USN journal.', 'MEDIUM'::detection_severity, 'SPLUNK'::detection_platform, 'T1070', 'Defense Evasion', 'Indicator Removal on Host', '{}', '{}', '| tstats `summariesonly` count values(Processes.process) as process values(Processes.parent_process) as parent_process min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process_name=fsutil.exe by Processes.user Processes.process_name Processes.parent_process_name Processes.dest  | `drop_dm_object_name(Processes)` | `ctime(firstTime)`| `ctime(lastTime)` | search process="*deletejournal*" AND process="*usn*"', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Endpoint Detection and Response"}', '{"EDR","Endpoint"}'),
('DET-0180', 'WMI Temporary Event Subscription', 'This search looks for the creation of WMI temporary event subscriptions.', 'MEDIUM'::detection_severity, 'SPLUNK'::detection_platform, 'T1047', 'Execution', 'Windows Management Instrumentation', '{}', '{}', 'sourcetype="wineventlog:microsoft-windows-wmi-activity/operational" EventCode=5860 Temporary | rex field=Message "NotificationQuery =\s+(?<query>[^|^$]+)" | search query!="SELECT * FROM Win32_ProcessStartTrace WHERE ProcessName = ''wsmprovhost.exe''" AND query!="SELECT * FROM __InstanceOperationEvent WHERE TargetInstance ISA ''AntiVirusProduct'' OR TargetInstance ISA ''FirewallProduct'' OR TargetInstance ISA ''AntiSpywareProduct''" | stats count min(_time) as firstTime max(_time) as lastTime by ComputerName, query  | `ctime(firstTime)`| `ctime(lastTime)`', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Windows Security"}', '{"Windows AD","Windows Endpoint"}'),
('DET-0181', 'Detect Excessive Account Lockouts From Endpoint', 'This search identifies endpoints that have caused a relatively high number of account lockouts in a short period.', 'HIGH'::detection_severity, 'SPLUNK'::detection_platform, 'T1078', 'Credential Access', 'Valid Accounts', '{}', '{}', '| tstats `summariesonly` count min(_time) as firstTime max(_time) as lastTime from datamodel=Change.All_Changes where nodename=All_Changes.Account_Management All_Changes.result="lockout" by All_Changes.dest All_Changes.result |`drop_dm_object_name("All_Changes")` |`drop_dm_object_name("Account_Management")`| `ctime(firstTime)` | `ctime(lastTime)` | search count > 5', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Authentication"}', '{"Identity Provider","Active Directory"}'),
('DET-0182', 'Suspicious HTTP redirects', 'Detects sequences of HTTP requests within a short period of time that suggests infection has taken place.', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1185', 'Collection', 'Man in the Browser', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Web Proxy / NGFW"}', '{"Web Proxy","Next-Gen Firewall"}'),
('DET-0183', 'Healthcare Worker Opening More Patient Records Than Usual', 'If a healthcare worker views more patient records than normal or more than their peers, it could be a sign that their system is infected, or that they are exfiltrating patient data.Alert Volume: Low', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1213', 'Collection', 'Data from Information Repositories', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Audit Trail"}', '{"Audit System"}'),
('DET-0184', 'Detect USB device insertion', 'The search is used to detect hosts that generate Windows Event ID 4663 for successful attempts to write to or read from a removable storage and Event ID 4656 for failures, which occurs when a USB drive is plugged in. In this scenario we are querying the Change_Analysis data model to look for Windows Event ID 4656 or 4663 where the priority of the affected host is marked as high in the ES Assets and Identity Framework.', 'HIGH'::detection_severity, 'SPLUNK'::detection_platform, 'T1052', 'Exfiltration', 'Exfiltration Over Physical Medium', '{}', '{}', '| tstats `summariesonly` count earliest(_time) AS earliest latest(_time) AS latest from datamodel=Change_Analysis where (nodename = All_Changes) All_Changes.result="Removable Storage device" (All_Changes.result_id=4663 OR All_Changes.result_id=4656) (All_Changes.src_priority=high) by All_Changes.dest | `drop_dm_object_name("All_Changes")`| `ctime(earliest)`| `ctime(latest)`', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Endpoint Detection and Response","DLP"}', '{"EDR","Endpoint","Data Loss Prevention"}'),
('DET-0185', 'Detect Many Unauthorized Access Attempts', 'Most login failures are due to failed passwords. Login failure to sensitive systems where the users simply aren''t authorized, though, can indicate malicious intent. Detect that.', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1110', 'Credential Access', 'Brute Force', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Authentication","Windows Security"}', '{"Identity Provider","Active Directory","Windows AD","Windows Endpoint"}'),
('DET-0186', 'Suspicious Email Attachment Extensions', 'This search looks for emails that have attachments with suspicious file extensions.', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1193', 'Initial Access', 'Spearphishing Attachment', '{}', '{}', '| tstats `summariesonly` count min(_time) as firstTime max(_time) as lastTime from datamodel=Email where All_Email.file_name="*" by All_Email.src_user, All_Email.file_name All_Email.message_id | `ctime(firstTime)` | `ctime(lastTime)` | `drop_dm_object_name("All_Email")` | `suspicious_email_attachments`', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Email","Email"}', '{"Email Gateway","Mail Server"}'),
('DET-0187', 'Web Browsing to Unauthorized Sites', 'Detect users who are persistently attempting to violate your proxy policy.', 'MEDIUM'::detection_severity, 'SPLUNK'::detection_platform, 'T1048', 'Exfiltration', 'Exfiltration Over Alternative Protocol', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Web Proxy / NGFW"}', '{"Web Proxy","Next-Gen Firewall"}'),
('DET-0188', 'Multiple Box Login Errors', 'Detects outliers in the timeseries of Box login failures per Box user.', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1110', 'Credential Access', 'Brute Force', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Audit Trail"}', '{"Audit System"}')
ON CONFLICT (rule_id) DO NOTHING;