INSERT INTO detections (
  rule_id, name, description, severity, platform,
  mitre_attack_id, mitre_tactic, mitre_technique,
  nist_controls, data_sources, query, query_language, tags,
  expected_alerts_per_day, expected_fp_rate, expected_mttd_hours,
  is_global, tenant_id, log_sources, device_types
) VALUES
('DET-0189', 'Old Passwords in Use', 'Detect active accounts with passwords that haven''t been updated in more than 120 days.', 'MEDIUM'::detection_severity, 'SPLUNK'::detection_platform, 'T1110', 'Credential Access', 'Brute Force', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Windows Security"}', '{"Windows AD","Windows Endpoint"}'),
('DET-0190', 'User Login with Local Credentials', 'Categorically, most interactive logins should use domain credentials. Detect when a new user logs on with local credentials that bypass most centralized logging and policy systems, but not Splunk!', 'HIGH'::detection_severity, 'SPLUNK'::detection_platform, 'T1078', 'Privilege Escalation', 'Valid Accounts', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Windows Security"}', '{"Windows AD","Windows Endpoint"}'),
('DET-0191', 'Suspicious Reg.exe Process', 'This search looks for reg.exe being launched from a command prompt not started by the user. When a user launches cmd.exe, the parent process is usually explorer.exe. This search filters out those instances.', 'MEDIUM'::detection_severity, 'SPLUNK'::detection_platform, 'T1112', 'Defense Evasion', 'Modify Registry', '{}', '{}', '| tstats `summariesonly` count min(_time) as firstTime max(_time) as lastTime FROM datamodel=Endpoint.Processes where Processes.parent_process_name != explorer.exe Processes.process_name =cmd.exe by Processes.user Processes.process_name Processes.parent_process_name Processes.dest Processes.process_id Processes.parent_process_id | `drop_dm_object_name("Processes")` | `ctime(firstTime)` | `ctime(lastTime)` | search [| tstats `summariesonly` count FROM datamodel=Endpoint.Processes where Processes.parent_process_name=cmd.exe Processes.process_name= reg.exe by Processes.parent_process_id Processes.dest Processes.process_name | `drop_dm_object_name("Processes")` | `ctime(firstTime)` | `ctime(lastTime)` | rename parent_process_id as process_id |dedup process_id| table process_id dest]', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Endpoint Detection and Response"}', '{"EDR","Endpoint"}'),
('DET-0192', 'Large Web Upload', 'Uses a basic threshold to detect a large web upload, which could be exfiltration from malware or a malicious insider.', 'MEDIUM'::detection_severity, 'SPLUNK'::detection_platform, 'T1041', 'Exfiltration', 'Exfiltration Over Command and Control Channel', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Web Proxy / NGFW"}', '{"Web Proxy","Next-Gen Firewall"}'),
('DET-0193', 'First Time Logon to New Server', 'Find users who logged into a new server for the first time.Alert Volume: Very High', 'CRITICAL'::detection_severity, 'SPLUNK'::detection_platform, 'T1021', 'Lateral Movement', 'Remote Services', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Authentication","Windows Security"}', '{"Identity Provider","Active Directory","Windows AD","Windows Endpoint"}'),
('DET-0194', 'Malicious AD Activity', 'Raises anomalies when the input data matches a set of predefined patterns in Microsoft Windows logs.', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1078', 'Persistence', 'Valid Accounts', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Windows Security"}', '{"Windows AD","Windows Endpoint"}'),
('DET-0195', 'Network Device Rebooted', 'Increases the risk score of network devices that have been rebooted.', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1089', 'Defense Evasion', 'Disabling Security Tools', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Configuration Management"}', '{}'),
('DET-0196', 'Unusually Long Content-Type Length', 'This search looks for unusually long strings in the Content-Type http header that the client sends the server.', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1320', 'Defense Evasion', 'Data Hiding', '{}', '{}', 'sourcetype=stream:http | eval cs_content_type_length = len(cs_content_type) | where cs_content_type_length > 100 | table endtime src_ip dest_ip cs_content_type_length cs_content_type url', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Web Server"}', '{}'),
('DET-0197', 'Detect PsExec With accepteula Flag', 'This search looks for events where <code>PsExec.exe</code> is run with the <code>accepteula</code> flag in the command line. PsExec is a built-in Windows utility that enables you to execute processes on other systems. It is fully interactive for console applications. This tool is widely used for launching interactive command prompts on remote systems. Threat actors leverage this extensively for executing code on compromised systems. If an attacker is running PsExec for the first time, they will be prompted to accept the end-user license agreement (EULA), which can be passed as the argument <code>accepteula</code> within the command line.', 'MEDIUM'::detection_severity, 'SPLUNK'::detection_platform, 'T1059', 'Execution', 'Command-Line Interface', '{}', '{}', '| tstats `summariesonly` values(Processes.process) as process min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process_name = PsExec.exe Processes.process = "*accepteula*" by Processes.process_name Processes.dest  Processes.parent_process_name | `drop_dm_object_name(Processes)`| `ctime(firstTime)`| `ctime(lastTime)`', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Endpoint Detection and Response"}', '{"EDR","Endpoint"}'),
('DET-0198', 'SIEM-DE-None-XX-Remote Registry Key modifications', 'This search monitors for remote modifications to registry keys.', 'MEDIUM'::detection_severity, 'SPLUNK'::detection_platform, NULL, 'Defense Evasion', 'None', '{}', '{}', '| tstats `summariesonly` count values(Registry.registry_key_name) as registry_key_name values(Registry.registry_path) as registry_path min(_time) as firstTime max(_time) as lastTime FROM datamodel=Endpoint.Registry where  Registry.registry_path="\\\\*"  by Registry.dest , Registry.status, Registry.user | `ctime(lastTime)` | `ctime(firstTime)` | `drop_dm_object_name(Registry)`', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Endpoint Detection and Response"}', '{"EDR","Endpoint"}'),
('DET-0199', 'Fake Windows Processes', 'This example finds processes normally run from Windows\System32 or Windows\SysWOW64, running from some other location. This can indicate a malicious process trying to hide as a legitimate process.Alert Volume: Low', 'LOW'::detection_severity, 'SPLUNK'::detection_platform, 'T1036', 'Defense Evasion', 'Masquerading', '{}', '{}', '-- No query defined', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Endpoint Detection and Response","Windows Security"}', '{"EDR","Endpoint","Windows AD","Windows Endpoint"}'),
('DET-0200', 'SIEM-E-None-XX-Detect S3 access from a new IP', 'This search looks at S3 bucket-access logs and detects new or previously unseen remote IP addresses that have successfully accessed an S3 bucket.', 'HIGH'::detection_severity, 'SPLUNK'::detection_platform, NULL, 'Execution', 'None', '{}', '{}', 'sourcetype=aws:s3:accesslogs http_status=200  [search sourcetype=aws:s3:accesslogs http_status=200 | stats earliest(_time) as firstTime latest(_time) as lastTime by bucket_name remote_ip | inputlookup append=t previously_seen_S3_access_from_remote_ip.csv | stats min(firstTime) as firstTime, max(lastTime) as lastTime by bucket_name remote_ip | outputlookup previously_seen_S3_access_from_remote_ip.csv | eval newIP=if(firstTime >= relative_time(now(), "-70m@m"), 1, 0) | where newIP=1 | convert ctime(firstTime) ctime(lastTime) | table bucket_name remote_ip]| iplocation remote_ip |rename remote_ip as src_ip | table _time bucket_name src_ip City Country operation request_uri', 'SPL'::query_language, '{}', NULL, NULL, NULL, TRUE, NULL, '{"Audit Trail","AWS","Web Server"}', '{"Audit System","AWS Cloud"}')
ON CONFLICT (rule_id) DO NOTHING;