-- ============================================================
-- 003_super_admin_seed.sql  [SUPERSEDED]
--
-- This file created the super admin with a bcrypt password_hash
-- for the legacy custom-JWT auth stack.
--
-- Since migrating to Supabase Auth (2026-06-19), passwords are
-- managed entirely by Supabase. This file is kept for git history
-- only. Use 005_cleanup_and_super_admin.sql instead.
-- ============================================================
